package curriculum

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/danielgtaylor/huma/v2"
)

const editorSchemaDraft = "https://json-schema.org/draft/2020-12/schema"

// EditorSchema is one generated structural schema for a curriculum authoring
// document. Semantic and cross-file validation remains the responsibility of
// Load and cmd/curriculum-check.
type EditorSchema struct {
	Filename string
	Data     []byte
}

type editorSchemaDefinition struct {
	filename    string
	title       string
	authoringTy reflect.Type
}

type editorSchemaDocument struct {
	Schema  string                  `json:"$schema"`
	Comment string                  `json:"$comment"`
	Ref     string                  `json:"$ref"`
	Defs    map[string]*huma.Schema `json:"$defs"`
}

var editorSchemaDefinitions = []editorSchemaDefinition{
	{filename: "course.schema.json", title: "Fonzytooter course metadata", authoringTy: reflect.TypeFor[courseAuthoring]()},
	{filename: "exercise.schema.json", title: "Fonzytooter exercise", authoringTy: reflect.TypeFor[exerciseAuthoring]()},
	{filename: "lesson-frontmatter.schema.json", title: "Fonzytooter lesson frontmatter", authoringTy: reflect.TypeFor[lessonFrontmatter]()},
	{filename: "module.schema.json", title: "Fonzytooter module metadata", authoringTy: reflect.TypeFor[moduleAuthoring]()},
	{filename: "review-item.schema.json", title: "Fonzytooter review item", authoringTy: reflect.TypeFor[reviewItemAuthoring]()},
	{filename: "sources.schema.json", title: "Fonzytooter source registry", authoringTy: reflect.TypeFor[sourceRegistry]()},
	{filename: "worksheet.schema.json", title: "Fonzytooter worksheet", authoringTy: reflect.TypeFor[worksheetAuthoring]()},
}

// GenerateEditorSchemas derives deterministic JSON Schema documents directly
// from the structs used to decode authored curriculum YAML and frontmatter.
func GenerateEditorSchemas() ([]EditorSchema, error) {
	generated := make([]EditorSchema, 0, len(editorSchemaDefinitions))
	for _, definition := range editorSchemaDefinitions {
		registry := huma.NewMapRegistry("#/$defs/", huma.DefaultSchemaNamer)
		root := registry.Schema(definition.authoringTy, true, definition.title)
		rootSchema := registry.SchemaFromRef(root.Ref)
		if rootSchema == nil {
			return nil, fmt.Errorf("generate %s: root schema was not registered", definition.filename)
		}
		rootSchema.Title = definition.title

		document := editorSchemaDocument{
			Schema:  editorSchemaDraft,
			Comment: "Code generated by server/cmd/curriculum-schema; DO NOT EDIT.",
			Ref:     root.Ref,
			Defs:    registry.Map(),
		}
		data, err := json.MarshalIndent(document, "", "  ")
		if err != nil {
			return nil, fmt.Errorf("generate %s: %w", definition.filename, err)
		}
		generated = append(generated, EditorSchema{
			Filename: definition.filename,
			Data:     append(data, '\n'),
		})
	}
	return generated, nil
}
